### ISSUE TITLE
Content in multiple lines

### ISSUE THREAD

**Issue by vsdmoraes** [joeleisner/purejs-mousetip#12]
Hey there!

I have a question. 

Is there a way to show the tooltip content in two or more lines?

Thanks,
Moraes.

**Comment by joeleisner** [comment]
Hey, @vsdmoraes !

You can accomplish this by simply adding valid HTML to a mousetip's message instead of just text. Here's an example:

```<div mousetip mousetip-msg="<p>Line one!</p><p>Line two!</p>"></div>```

Hope that helped!
