### ISSUE TITLE
Missing export statement on es2015 version

### ISSUE THREAD

**Issue by gt0p** [joeleisner/purejs-mousetip#14]
I didn't manage to import es20115 module on my code without editing mousetip.es2015.js file and adding a `modules.exports = MouseTip;` line.

Is there other way to import it without editing your files ?

Thanks for this lightweight tool.

**Comment by joeleisner** [comment]
Hey, @gt0p!

Module versions of this library are only available within the NPM package, and not within the releases on GitHub. To install the package, simply run `npm i purejs-mousetip` in your project directory. Under `node_modules/purejs-mousetip/dist/modules`, there are two modules available for use:

1. **mousetip.common.js** - Using the CommonJS (Node) module format, i.e. `module.exports = MouseTip;`
2. **mousetip.es2015.js** - Using the new `import` module spec, i.e. `export default MouseTip;`

In your case, you will want to use the `mousetip.common.js` file (`node_modules/purejs-mousetip/dist/modules/mousetip.common.js`).

Hope this helps! I'm going to close this issue, but feel free to continue the conversation.

**Comment by gt0p** [comment]
I was trying to use file mousetip.es2015.js which is outside of folder modules and thats why I had the problem to import it. Now I use mousetip.common.js as you suggest.

Thanks, have a nice day.
