### ISSUE TITLE
Duplicate mouse tips in some weird cases

### ISSUE THREAD

**Issue by vinayakpatil** [joeleisner/purejs-mousetip#15]
![image](https://user-images.githubusercontent.com/3096223/54978547-af057480-4fc6-11e9-9501-e03343f7eea7.png)

Suggestion: Can we invoke `deleteMouseTip` before generating any new mousetip in `createMouseTip`?

**Comment by joeleisner** [comment]
Hey, @vinayakpatil !

I'll look into this to see what I can do to remedy this issue. I have a few questions as I'm not able to duplicate this within my local environment:

1. How many instances of MouseTip are being used?
2. What configuration object is being passed for this/these instance(s)?

Thanks!

**Comment by vinayakpatil** [comment]
@joeleisner thanks for a quick turnaround.

there is only one instance which is triggered like below, but this duplicate tip issue occurs intermittently where I can see that `mouseleave` is not called for respective `mouseenter`.
```
this._mousetip = new MouseTip();
this._mousetip.start();
```

**Comment by joeleisner** [comment]
Hey, @vinayakpatil !

Hmmm... I'm thinking this may have to do with how `mouseenter` and `mouseleave` are called/treated with different elements. Can you let me know what browser you're using when you see this issue arise? I'd like to duplicate the issue on my end, but I'm having trouble doing so.

**Comment by joeleisner** [comment]
Due to almost 2 months of inactivity, I'm going to close this ticket; I was unable to find the culprit behind this issue.
