### ISSUE TITLE
add msg to constructor

### ISSUE THREAD

**Issue by benintech** [joeleisner/purejs-mousetip#16]
Hi,
Nice script !

Not an issue here, but rather a feature request.

I added a little feature, to be able to pass the tooltip message to the constructor (so the HTML files aren't too cluttered, and all my tooltip messages are defined in some .js or even .json file).

I think you should add this feature to your main script :

<pre>
constructor(settings) {    
    const {    
        cssZIndex = '9999',    
        (...)    
        <b>msg = ""</b>    
    } = settings || {};
    (...)
    <b>this.msg             = msg;</b>
    (...)
}
createMouseTip(event) {
    (...)
    const message  = this.element.getAttribute(this.selector + '-msg') <b>|| this.msg</b>;
    (...)
}
(...)
</pre>

Now my mousetip can be defined like this :
 <pre>
var myMouseTipText = 'Some text';
myMouseTipText += '&lt;br/&gt;';
myMouseTipText += 'And so on...'; 

let myMouseTip = new MouseTip({
    cssPadding      : '15px',
    <b>msg             : myMouseTipText</b>,
    cssBorderRadius : '4px',
    cssBackground   : 'lightgreen',
    cssColor        : 'blue',
    selector        : 'mousetip="myMouseTip"'
});
myMouseTip.start();
</pre>

**Comment by joeleisner** [comment]
Hey, @benintech !

This is pretty interesting! There's definitely a lot of use cases for this, so I'll be looking into adding this in an upcoming release. Thanks for the suggestion!

**Comment by joeleisner** [comment]
Hey, @benintech !

I've added your suggestion to the 2.1.4 release! I should be pushing this update out later today, so keep an eye out. Thanks again for your suggestion!

**Comment by joeleisner** [comment]
Hey, @benintech !

One last update: It's live! You should be able to pull down version 2.1.4 from NPM very soon!

Once again, thanks for the suggestion!

**Comment by benintech** [comment]
Great, thanks for your quick response !!!

**Comment by joeleisner** [comment]
Hey, @benintech !

No problem.
