### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by vinayakpatil** [joeleisner/purejs-mousetip#8]

**Comment by joeleisner** [comment]
Hey, @vinayakpatil ! Just to clarify this issue, are you wondering if this script "plays nice" with Typescript? Or are you wondering if I have any intention of making a Typescript version of the script? Let me know!

**Comment by vinayakpatil** [comment]
@joeleisner Library structure is not suitable for consumption inside typescript project for modern bundlers like rollup or Angular CLI.

Question - How can I import `MouseTip` class from node_modules?

Reference: https://github.com/rollup/rollup-starter-lib/blob/master/package.json

**Comment by joeleisner** [comment]
Hey, @vinayakpatil ! Ahh, okay. I'll add supporting CommonJS and ES2015 modules to my upcoming features list. Thanks for the recommendation!
